// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_PM25;
extern lv_obj_t * ui_PM10;
extern lv_obj_t * ui_pm25val;
extern lv_obj_t * ui_pm10val;
extern lv_obj_t * ui_unit1;
extern lv_obj_t * ui_unit2;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_statusLabel;
extern lv_obj_t * ui_Status;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

