// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2;
lv_obj_t * ui_PM25;
lv_obj_t * ui_PM10;
lv_obj_t * ui_pm25val;
lv_obj_t * ui_pm10val;
lv_obj_t * ui_unit1;
lv_obj_t * ui_unit2;
lv_obj_t * ui_title;
lv_obj_t * ui_statusLabel;
lv_obj_t * ui_Status;

// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_PM25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM25, -82);
    lv_obj_set_y(ui_PM25, -44);
    lv_obj_set_align(ui_PM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM25, "PM2.5:");
    lv_obj_set_style_text_color(ui_PM25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PM25, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PM25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PM25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM25, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PM25, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM25, lv_color_hex(0xDB7B28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PM25, lv_color_hex(0xF8923B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_PM25, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PM25, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PM25, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PM25, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PM25, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_PM10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PM10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PM10, -82);
    lv_obj_set_y(ui_PM10, 16);
    lv_obj_set_align(ui_PM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PM10, "PM10 :");
    lv_obj_set_style_text_color(ui_PM10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_PM10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PM10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PM10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PM10, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PM10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM10, lv_color_hex(0x0076DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PM10, lv_color_hex(0x52D4F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_PM10, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PM10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PM10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PM10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PM10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_pm25val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25val, 57);
    lv_obj_set_y(ui_pm25val, -58);
    lv_obj_set_align(ui_pm25val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25val, "0");
    lv_obj_set_style_text_color(ui_pm25val, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25val, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_pm10val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10val, 57);
    lv_obj_set_y(ui_pm10val, 7);
    lv_obj_set_align(ui_pm10val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10val, "0");
    lv_obj_set_style_text_color(ui_pm10val, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10val, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unit1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_unit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unit1, 59);
    lv_obj_set_y(ui_unit1, -31);
    lv_obj_set_align(ui_unit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unit1, "ug/m3");
    lv_obj_set_style_text_color(ui_unit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unit2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_unit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unit2, 60);
    lv_obj_set_y(ui_unit2, 35);
    lv_obj_set_align(ui_unit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unit2, "ug/m3");
    lv_obj_set_style_text_color(ui_unit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title, 0);
    lv_obj_set_y(ui_title, -104);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "PM ANALYZER");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0xF39F02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, -108);
    lv_obj_set_y(ui_statusLabel, 81);
    lv_obj_set_align(ui_statusLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_statusLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_statusLabel, "Air Quality:");
    lv_obj_set_style_text_color(ui_statusLabel, lv_color_hex(0xF39F02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Status, 42);
    lv_obj_set_y(ui_Status, 81);
    lv_obj_set_align(ui_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Status, "Very Good");
    lv_obj_set_style_text_color(ui_Status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Status, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_PM25 = NULL;
    ui_PM10 = NULL;
    ui_pm25val = NULL;
    ui_pm10val = NULL;
    ui_unit1 = NULL;
    ui_unit2 = NULL;
    ui_title = NULL;
    ui_statusLabel = NULL;
    ui_Status = NULL;

}
